/******************************************************************************
 MyCommands.h

      Header File For Command Symbols

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª

  This file is regenerated each time.

 ******************************************************************************/

#pragma once


