/******************************************************************************
 CApp.h

      Header File For CApp Application Class

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª 12:55 AM Thu, Mar 21, 1996

  This file is only generated once. You can modify it by redefining
  in the placeholder definitions and adding any new methods and
  data members you wish.

  If you change the name of the application, a fresh version of this
  file will be generated. If you have made any changes to the file
  with the old name, you will have to copy those changes to the new
  file by hand.

 ******************************************************************************/

#pragma once

#include "x_CApp.h"

#include <CDialog.h>

class CApp : public x_CApp
{
public:

      TCL_DECLARE_CLASS

      void  ICApp(void);

  virtual  void   ForceClassReferences(void);
  virtual  void   DoCommand(long theCommand);

      // Remove this function if you do not have
      // multiple document types

  virtual  OSType   GetDocTypeFromDialog(CDialogDirector *dialog);
};

//  File Types
//
//  Change the #defines below to reflect the file types
//  your application actually creates or opens

#define  kNumFileTypes  1
#define  kFileType1    'TEXT'
#define kFileType2    'TEXT'
#define kFileType3    'TEXT'
#define kFileType4    'TEXT'

