/******************************************************************************
 CMain.h

      Header File For CMain Document Class

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª 12:55 AM Thu, Mar 21, 1996

  This file is only generated once. You can modify it by extending
  the placeholder definitions and adding any new methods and
  data members you wish.

  If you change the name of the document class, a fresh version of this
  file will be generated. If you have made any changes to the file
  with the old name, you will have to copy those changes to the new
  file by hand.

 ******************************************************************************/

#pragma once

#include "x_CMain.h"

class CMain : public x_CMain

{
public:

  TCL_DECLARE_CLASS


  void  ICMain(void);

  virtual  void  MakeNewContents(void);
  virtual  void  ContentsToWindow(void);
  virtual  void  WindowToContents(void);
};

  // If you have multiple document classes, you must change
  // the file type below to the appropriate type for this class.
  // If not, this #define is not used.

#define CMainFType 'TEXT'

