/******************************************************************************
 CSaver_CMain.cp

      Generate CSaver template

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª 12:55 AM Thu, Mar 21, 1996

  This file is only generated once.

 ******************************************************************************/

#include <CSaver.h>

#pragma template_access public

#define GENERATE_TEMPLATE
#include "ItsContents_CMain.h"

#include <CSaver.tem>

