/******************************************************************************
 ItsContents_CMain.h

      Define class of CSaver itsContents variable
      for the CMain document class

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª 12:55 AM Thu, Mar 21, 1996

  This file is only generated once.

  YOU NEED TO MODIFY THIS FILE:

    Change every instance of CCollaborator below to the
    name of the actual class of your itsContents object

 ******************************************************************************/

#pragma once

#include "CCollaborator.h"

#define ITSCONTENTS_CMain CCollaborator

#ifdef GENERATE_TEMPLATE

#pragma template CSaver<CCollaborator>

#endif

