/******************************************************************************
 MainItems.h

        Main Item Constants

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª

  This file is rewritten each time you generate code. You should not
  make changes to this file.

  If you want to change how Visual Architect generates this file, you can
  change the template for this file. It is "Items.h" in the Visual Architect
  Templates folder.

 ******************************************************************************/

#pragma once


  //  Item numbers for each item.
  //
  //  Use TCLGetItemPointer (ViewUtilities) to convert these
  //  item numbers to a pointer to the named item.

enum
{
  Main_Begin_,
  kMain_Pict1 = 1,
  kMain_Pict1ID = 1L,
  kMain_Stat2 = 2,
  kMain_Stat2ID = 2L,
  Main_End_
};

