/******************************************************************************
 References.h

    References to Object I/O classes in TCL

  Generated by Visual Architect. 12:55 AM Thu, Mar 21, 1996

  This file is only generated once per project. You should
  not need to change it.

 ******************************************************************************/

#pragma once

#include "TCLForceReferences.h"

void  ReferenceStdClasses();


