/******************************************************************************
 x_CApp.h

      Header File For CApp "Lower-Layer" Application Class

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª 12:55 AM Thu, Mar 21, 1996

  This file is rewritten each time you generate code. You should not
  make changes to this file; changes should go in the CApp.h
  file, instead.

  If you want to change how Visual Architect generates this file, you can
  change the template for this file. It is "_App.h" in the Visual Architect
  Templates folder.

 ******************************************************************************/

#pragma once

#include <CApplication.h>

class CFile;
class CDialogDirector;
class CDocument;

class x_CApp : public CApplication
{
public:

  TCL_DECLARE_CLASS

  void      Ix_CApp(short extraMasters, Size aRainyDayFund,
                Size aCriticalBalance, Size aToolboxBalance);
  virtual  void  SetUpFileParameters(void);
  virtual  void  SetUpMenus(void);
  virtual  void   ForceClassReferences(void);

  virtual  void   DoCommand(long theCommand);

  virtual  void   CreateDocument(void);
  virtual  void   OpenDocument(SFReply *macSFReply);


  virtual Boolean  FileAlreadyOpen(FSSpec *fileSpec);
};



