/******************************************************************************
 x_CMain.h

      Header File For CMain Lower-Layer Document Class

  Copyright © 1996 Esoft International. All rights reserved.

  Generated by Visual Architectª

  This file is rewritten each time you generate code. You should not
  make changes to this file; changes should go in the My.h
  file, instead.

  If you want to change how Visual Architect generates this file, you can
  change the template for this file. It is "_Doc.h" in the Visual Architect
  Templates folder.

 ******************************************************************************/

#pragma once

#include "CSaver.h"
class CPicture;
class CStaticText;

#include "ItsContents_CMain.h"

#define x_CMain_super  CSaver<ITSCONTENTS_CMain>

class CFile;

class x_CMain : public x_CMain_super

{
public:

  TCL_DECLARE_CLASS

                    // Pointers to panes in window
  CPicture  *fMain_Pict1;
  CStaticText  *fMain_Stat2;

  void   Ix_CMain(void);


protected:
  virtual  void  MakeNewWindow(void);

  virtual void  FailOpen(FSSpec *spec);
  virtual void  PositionWindow(void);

};

#define  CVueCMain  128

